// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: management/data_transformation.proto

package managementpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectionsDataTransformationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*ProjectionsDataTransformationRequest_Init
	//	*ProjectionsDataTransformationRequest_Data
	Payload isProjectionsDataTransformationRequest_Payload `protobuf_oneof:"payload"`
}

func (x *ProjectionsDataTransformationRequest) Reset() {
	*x = ProjectionsDataTransformationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_data_transformation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectionsDataTransformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionsDataTransformationRequest) ProtoMessage() {}

func (x *ProjectionsDataTransformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_data_transformation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionsDataTransformationRequest.ProtoReflect.Descriptor instead.
func (*ProjectionsDataTransformationRequest) Descriptor() ([]byte, []int) {
	return file_management_data_transformation_proto_rawDescGZIP(), []int{0}
}

func (m *ProjectionsDataTransformationRequest) GetPayload() isProjectionsDataTransformationRequest_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ProjectionsDataTransformationRequest) GetInit() *ProjectionsTransformData {
	if x, ok := x.GetPayload().(*ProjectionsDataTransformationRequest_Init); ok {
		return x.Init
	}
	return nil
}

func (x *ProjectionsDataTransformationRequest) GetData() *ProjectionsTransformedData {
	if x, ok := x.GetPayload().(*ProjectionsDataTransformationRequest_Data); ok {
		return x.Data
	}
	return nil
}

type isProjectionsDataTransformationRequest_Payload interface {
	isProjectionsDataTransformationRequest_Payload()
}

type ProjectionsDataTransformationRequest_Init struct {
	Init *ProjectionsTransformData `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type ProjectionsDataTransformationRequest_Data struct {
	Data *ProjectionsTransformedData `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*ProjectionsDataTransformationRequest_Init) isProjectionsDataTransformationRequest_Payload() {}

func (*ProjectionsDataTransformationRequest_Data) isProjectionsDataTransformationRequest_Payload() {}

type ProjectionsTransformData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CrudType string `protobuf:"bytes,1,opt,name=crud_type,json=crudType,proto3" json:"crud_type,omitempty"`
}

func (x *ProjectionsTransformData) Reset() {
	*x = ProjectionsTransformData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_data_transformation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectionsTransformData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionsTransformData) ProtoMessage() {}

func (x *ProjectionsTransformData) ProtoReflect() protoreflect.Message {
	mi := &file_management_data_transformation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionsTransformData.ProtoReflect.Descriptor instead.
func (*ProjectionsTransformData) Descriptor() ([]byte, []int) {
	return file_management_data_transformation_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectionsTransformData) GetCrudType() string {
	if x != nil {
		return x.CrudType
	}
	return ""
}

type ProjectionsDataToTransform struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CrudType string            `protobuf:"bytes,1,opt,name=crud_type,json=crudType,proto3" json:"crud_type,omitempty"`
	TenantId string            `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id       string            `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Data     map[string]string `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ProjectionsDataToTransform) Reset() {
	*x = ProjectionsDataToTransform{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_data_transformation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectionsDataToTransform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionsDataToTransform) ProtoMessage() {}

func (x *ProjectionsDataToTransform) ProtoReflect() protoreflect.Message {
	mi := &file_management_data_transformation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionsDataToTransform.ProtoReflect.Descriptor instead.
func (*ProjectionsDataToTransform) Descriptor() ([]byte, []int) {
	return file_management_data_transformation_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectionsDataToTransform) GetCrudType() string {
	if x != nil {
		return x.CrudType
	}
	return ""
}

func (x *ProjectionsDataToTransform) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ProjectionsDataToTransform) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectionsDataToTransform) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type ProjectionsTransformedData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CrudType string            `protobuf:"bytes,1,opt,name=crud_type,json=crudType,proto3" json:"crud_type,omitempty"`
	TenantId string            `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id       string            `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Data     map[string]string `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ProjectionsTransformedData) Reset() {
	*x = ProjectionsTransformedData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_data_transformation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectionsTransformedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionsTransformedData) ProtoMessage() {}

func (x *ProjectionsTransformedData) ProtoReflect() protoreflect.Message {
	mi := &file_management_data_transformation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionsTransformedData.ProtoReflect.Descriptor instead.
func (*ProjectionsTransformedData) Descriptor() ([]byte, []int) {
	return file_management_data_transformation_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectionsTransformedData) GetCrudType() string {
	if x != nil {
		return x.CrudType
	}
	return ""
}

func (x *ProjectionsTransformedData) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ProjectionsTransformedData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectionsTransformedData) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_management_data_transformation_proto protoreflect.FileDescriptor

var file_management_data_transformation_proto_rawDesc = []byte{
	0x0a, 0x24, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x22, 0xab, 0x01, 0x0a, 0x24, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x44, 0x61, 0x74, 0x61, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x04, 0x69,
	0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x48,
	0x00, 0x52, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x12, 0x3c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0x37, 0x0a, 0x18, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09,
	0x63, 0x72, 0x75, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x72, 0x75, 0x64, 0x54, 0x79, 0x70, 0x65, 0x22, 0xe5, 0x01, 0x0a, 0x1a, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x44, 0x61, 0x74, 0x61, 0x54, 0x6f, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x72, 0x75, 0x64,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x75,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x44, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x30, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x44, 0x61, 0x74, 0x61, 0x54, 0x6f, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x37, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0xe5, 0x01, 0x0a, 0x1a, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x72, 0x75, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x75, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x44, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x1a, 0x37, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_management_data_transformation_proto_rawDescOnce sync.Once
	file_management_data_transformation_proto_rawDescData = file_management_data_transformation_proto_rawDesc
)

func file_management_data_transformation_proto_rawDescGZIP() []byte {
	file_management_data_transformation_proto_rawDescOnce.Do(func() {
		file_management_data_transformation_proto_rawDescData = protoimpl.X.CompressGZIP(file_management_data_transformation_proto_rawDescData)
	})
	return file_management_data_transformation_proto_rawDescData
}

var file_management_data_transformation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_management_data_transformation_proto_goTypes = []interface{}{
	(*ProjectionsDataTransformationRequest)(nil), // 0: management.ProjectionsDataTransformationRequest
	(*ProjectionsTransformData)(nil),             // 1: management.ProjectionsTransformData
	(*ProjectionsDataToTransform)(nil),           // 2: management.ProjectionsDataToTransform
	(*ProjectionsTransformedData)(nil),           // 3: management.ProjectionsTransformedData
	nil,                                          // 4: management.ProjectionsDataToTransform.DataEntry
	nil,                                          // 5: management.ProjectionsTransformedData.DataEntry
}
var file_management_data_transformation_proto_depIdxs = []int32{
	1, // 0: management.ProjectionsDataTransformationRequest.init:type_name -> management.ProjectionsTransformData
	3, // 1: management.ProjectionsDataTransformationRequest.data:type_name -> management.ProjectionsTransformedData
	4, // 2: management.ProjectionsDataToTransform.data:type_name -> management.ProjectionsDataToTransform.DataEntry
	5, // 3: management.ProjectionsTransformedData.data:type_name -> management.ProjectionsTransformedData.DataEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_management_data_transformation_proto_init() }
func file_management_data_transformation_proto_init() {
	if File_management_data_transformation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_management_data_transformation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectionsDataTransformationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_data_transformation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectionsTransformData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_data_transformation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectionsDataToTransform); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_data_transformation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectionsTransformedData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_management_data_transformation_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ProjectionsDataTransformationRequest_Init)(nil),
		(*ProjectionsDataTransformationRequest_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_management_data_transformation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_management_data_transformation_proto_goTypes,
		DependencyIndexes: file_management_data_transformation_proto_depIdxs,
		MessageInfos:      file_management_data_transformation_proto_msgTypes,
	}.Build()
	File_management_data_transformation_proto = out.File
	file_management_data_transformation_proto_rawDesc = nil
	file_management_data_transformation_proto_goTypes = nil
	file_management_data_transformation_proto_depIdxs = nil
}
