// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: management/data_transformation.proto

package managementpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataTransformationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//
	//	*DataTransformationRequest_Init
	//	*DataTransformationRequest_Data
	Payload isDataTransformationRequest_Payload `protobuf_oneof:"payload"`
}

func (x *DataTransformationRequest) Reset() {
	*x = DataTransformationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_data_transformation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataTransformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataTransformationRequest) ProtoMessage() {}

func (x *DataTransformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_data_transformation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataTransformationRequest.ProtoReflect.Descriptor instead.
func (*DataTransformationRequest) Descriptor() ([]byte, []int) {
	return file_management_data_transformation_proto_rawDescGZIP(), []int{0}
}

func (m *DataTransformationRequest) GetPayload() isDataTransformationRequest_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *DataTransformationRequest) GetInit() *TransformData {
	if x, ok := x.GetPayload().(*DataTransformationRequest_Init); ok {
		return x.Init
	}
	return nil
}

func (x *DataTransformationRequest) GetData() *TransformedData {
	if x, ok := x.GetPayload().(*DataTransformationRequest_Data); ok {
		return x.Data
	}
	return nil
}

type isDataTransformationRequest_Payload interface {
	isDataTransformationRequest_Payload()
}

type DataTransformationRequest_Init struct {
	Init *TransformData `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type DataTransformationRequest_Data struct {
	Data *TransformedData `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*DataTransformationRequest_Init) isDataTransformationRequest_Payload() {}

func (*DataTransformationRequest_Data) isDataTransformationRequest_Payload() {}

type TransformData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CrudType string `protobuf:"bytes,1,opt,name=crud_type,json=crudType,proto3" json:"crud_type,omitempty"`
}

func (x *TransformData) Reset() {
	*x = TransformData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_data_transformation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransformData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformData) ProtoMessage() {}

func (x *TransformData) ProtoReflect() protoreflect.Message {
	mi := &file_management_data_transformation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformData.ProtoReflect.Descriptor instead.
func (*TransformData) Descriptor() ([]byte, []int) {
	return file_management_data_transformation_proto_rawDescGZIP(), []int{1}
}

func (x *TransformData) GetCrudType() string {
	if x != nil {
		return x.CrudType
	}
	return ""
}

type DataToTransform struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CrudType string            `protobuf:"bytes,1,opt,name=crud_type,json=crudType,proto3" json:"crud_type,omitempty"`
	TenantId string            `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id       string            `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Data     map[string]string `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *DataToTransform) Reset() {
	*x = DataToTransform{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_data_transformation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataToTransform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataToTransform) ProtoMessage() {}

func (x *DataToTransform) ProtoReflect() protoreflect.Message {
	mi := &file_management_data_transformation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataToTransform.ProtoReflect.Descriptor instead.
func (*DataToTransform) Descriptor() ([]byte, []int) {
	return file_management_data_transformation_proto_rawDescGZIP(), []int{2}
}

func (x *DataToTransform) GetCrudType() string {
	if x != nil {
		return x.CrudType
	}
	return ""
}

func (x *DataToTransform) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DataToTransform) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataToTransform) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type TransformedData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CrudType string            `protobuf:"bytes,1,opt,name=crud_type,json=crudType,proto3" json:"crud_type,omitempty"`
	TenantId string            `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id       string            `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Data     map[string]string `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TransformedData) Reset() {
	*x = TransformedData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_data_transformation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransformedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformedData) ProtoMessage() {}

func (x *TransformedData) ProtoReflect() protoreflect.Message {
	mi := &file_management_data_transformation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformedData.ProtoReflect.Descriptor instead.
func (*TransformedData) Descriptor() ([]byte, []int) {
	return file_management_data_transformation_proto_rawDescGZIP(), []int{3}
}

func (x *TransformedData) GetCrudType() string {
	if x != nil {
		return x.CrudType
	}
	return ""
}

func (x *TransformedData) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TransformedData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransformedData) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_management_data_transformation_proto protoreflect.FileDescriptor

var file_management_data_transformation_proto_rawDesc = []byte{
	0x0a, 0x24, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x22, 0x8a, 0x01, 0x0a, 0x19, 0x44, 0x61, 0x74, 0x61, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2f, 0x0a, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x69, 0x6e, 0x69,
	0x74, 0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22,
	0x2c, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x72, 0x75, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x75, 0x64, 0x54, 0x79, 0x70, 0x65, 0x22, 0xcf, 0x01,
	0x0a, 0x0f, 0x44, 0x61, 0x74, 0x61, 0x54, 0x6f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72,
	0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x72, 0x75, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x75, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x39, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x6f, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x37, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0xcf, 0x01, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x64, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x72, 0x75, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x75, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x39, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f,
	0x72, 0x6d, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x37, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_management_data_transformation_proto_rawDescOnce sync.Once
	file_management_data_transformation_proto_rawDescData = file_management_data_transformation_proto_rawDesc
)

func file_management_data_transformation_proto_rawDescGZIP() []byte {
	file_management_data_transformation_proto_rawDescOnce.Do(func() {
		file_management_data_transformation_proto_rawDescData = protoimpl.X.CompressGZIP(file_management_data_transformation_proto_rawDescData)
	})
	return file_management_data_transformation_proto_rawDescData
}

var file_management_data_transformation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_management_data_transformation_proto_goTypes = []interface{}{
	(*DataTransformationRequest)(nil), // 0: management.DataTransformationRequest
	(*TransformData)(nil),             // 1: management.TransformData
	(*DataToTransform)(nil),           // 2: management.DataToTransform
	(*TransformedData)(nil),           // 3: management.TransformedData
	nil,                               // 4: management.DataToTransform.DataEntry
	nil,                               // 5: management.TransformedData.DataEntry
}
var file_management_data_transformation_proto_depIdxs = []int32{
	1, // 0: management.DataTransformationRequest.init:type_name -> management.TransformData
	3, // 1: management.DataTransformationRequest.data:type_name -> management.TransformedData
	4, // 2: management.DataToTransform.data:type_name -> management.DataToTransform.DataEntry
	5, // 3: management.TransformedData.data:type_name -> management.TransformedData.DataEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_management_data_transformation_proto_init() }
func file_management_data_transformation_proto_init() {
	if File_management_data_transformation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_management_data_transformation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataTransformationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_data_transformation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransformData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_data_transformation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataToTransform); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_data_transformation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransformedData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_management_data_transformation_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*DataTransformationRequest_Init)(nil),
		(*DataTransformationRequest_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_management_data_transformation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_management_data_transformation_proto_goTypes,
		DependencyIndexes: file_management_data_transformation_proto_depIdxs,
		MessageInfos:      file_management_data_transformation_proto_msgTypes,
	}.Build()
	File_management_data_transformation_proto = out.File
	file_management_data_transformation_proto_rawDesc = nil
	file_management_data_transformation_proto_goTypes = nil
	file_management_data_transformation_proto_depIdxs = nil
}
