// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: management/migration.proto

package managementpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectionsEnumType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *ProjectionsEnumType) Reset() {
	*x = ProjectionsEnumType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectionsEnumType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionsEnumType) ProtoMessage() {}

func (x *ProjectionsEnumType) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionsEnumType.ProtoReflect.Descriptor instead.
func (*ProjectionsEnumType) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectionsEnumType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectionsEnumType) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type ProjectionsProjectionType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Directives []*ProjectionsTypeDirective `protobuf:"bytes,2,rep,name=directives,proto3" json:"directives,omitempty"`
	Fields     []*ProjectionsTypeField     `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *ProjectionsProjectionType) Reset() {
	*x = ProjectionsProjectionType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectionsProjectionType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionsProjectionType) ProtoMessage() {}

func (x *ProjectionsProjectionType) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionsProjectionType.ProtoReflect.Descriptor instead.
func (*ProjectionsProjectionType) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectionsProjectionType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectionsProjectionType) GetDirectives() []*ProjectionsTypeDirective {
	if x != nil {
		return x.Directives
	}
	return nil
}

func (x *ProjectionsProjectionType) GetFields() []*ProjectionsTypeField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ProjectionsCrudType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Directives []*ProjectionsTypeDirective `protobuf:"bytes,2,rep,name=directives,proto3" json:"directives,omitempty"`
	Fields     []*ProjectionsTypeField     `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *ProjectionsCrudType) Reset() {
	*x = ProjectionsCrudType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectionsCrudType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionsCrudType) ProtoMessage() {}

func (x *ProjectionsCrudType) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionsCrudType.ProtoReflect.Descriptor instead.
func (*ProjectionsCrudType) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectionsCrudType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectionsCrudType) GetDirectives() []*ProjectionsTypeDirective {
	if x != nil {
		return x.Directives
	}
	return nil
}

func (x *ProjectionsCrudType) GetFields() []*ProjectionsTypeField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ProjectionsNestedType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Directives []*ProjectionsTypeDirective `protobuf:"bytes,2,rep,name=directives,proto3" json:"directives,omitempty"`
	Fields     []*ProjectionsTypeField     `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *ProjectionsNestedType) Reset() {
	*x = ProjectionsNestedType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectionsNestedType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionsNestedType) ProtoMessage() {}

func (x *ProjectionsNestedType) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionsNestedType.ProtoReflect.Descriptor instead.
func (*ProjectionsNestedType) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectionsNestedType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectionsNestedType) GetDirectives() []*ProjectionsTypeDirective {
	if x != nil {
		return x.Directives
	}
	return nil
}

func (x *ProjectionsNestedType) GetFields() []*ProjectionsTypeField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ProjectionsTypeField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type       []string                    `protobuf:"bytes,2,rep,name=type,proto3" json:"type,omitempty"`
	Directives []*ProjectionsTypeDirective `protobuf:"bytes,3,rep,name=directives,proto3" json:"directives,omitempty"`
}

func (x *ProjectionsTypeField) Reset() {
	*x = ProjectionsTypeField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectionsTypeField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionsTypeField) ProtoMessage() {}

func (x *ProjectionsTypeField) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionsTypeField.ProtoReflect.Descriptor instead.
func (*ProjectionsTypeField) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectionsTypeField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectionsTypeField) GetType() []string {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ProjectionsTypeField) GetDirectives() []*ProjectionsTypeDirective {
	if x != nil {
		return x.Directives
	}
	return nil
}

type ProjectionsTypeDirective struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments []*ProjectionsTypeArgument `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty"`
}

func (x *ProjectionsTypeDirective) Reset() {
	*x = ProjectionsTypeDirective{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectionsTypeDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionsTypeDirective) ProtoMessage() {}

func (x *ProjectionsTypeDirective) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionsTypeDirective.ProtoReflect.Descriptor instead.
func (*ProjectionsTypeDirective) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{5}
}

func (x *ProjectionsTypeDirective) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectionsTypeDirective) GetArguments() []*ProjectionsTypeArgument {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type ProjectionsTypeArgument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ProjectionsTypeArgument) Reset() {
	*x = ProjectionsTypeArgument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectionsTypeArgument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionsTypeArgument) ProtoMessage() {}

func (x *ProjectionsTypeArgument) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionsTypeArgument.ProtoReflect.Descriptor instead.
func (*ProjectionsTypeArgument) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{6}
}

func (x *ProjectionsTypeArgument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectionsTypeArgument) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ProjectionsRegisterMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DangerouslyRemoveGdprFields bool                         `protobuf:"varint,1,opt,name=dangerouslyRemoveGdprFields,proto3" json:"dangerouslyRemoveGdprFields,omitempty"`
	ProjectionTypes             []*ProjectionsProjectionType `protobuf:"bytes,2,rep,name=projectionTypes,proto3" json:"projectionTypes,omitempty"`
	CrudTypes                   []*ProjectionsCrudType       `protobuf:"bytes,3,rep,name=crudTypes,proto3" json:"crudTypes,omitempty"`
	Enums                       []*ProjectionsEnumType       `protobuf:"bytes,4,rep,name=enums,proto3" json:"enums,omitempty"`
	NestedTypes                 []*ProjectionsNestedType     `protobuf:"bytes,5,rep,name=nestedTypes,proto3" json:"nestedTypes,omitempty"`
}

func (x *ProjectionsRegisterMigrationRequest) Reset() {
	*x = ProjectionsRegisterMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectionsRegisterMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionsRegisterMigrationRequest) ProtoMessage() {}

func (x *ProjectionsRegisterMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionsRegisterMigrationRequest.ProtoReflect.Descriptor instead.
func (*ProjectionsRegisterMigrationRequest) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectionsRegisterMigrationRequest) GetDangerouslyRemoveGdprFields() bool {
	if x != nil {
		return x.DangerouslyRemoveGdprFields
	}
	return false
}

func (x *ProjectionsRegisterMigrationRequest) GetProjectionTypes() []*ProjectionsProjectionType {
	if x != nil {
		return x.ProjectionTypes
	}
	return nil
}

func (x *ProjectionsRegisterMigrationRequest) GetCrudTypes() []*ProjectionsCrudType {
	if x != nil {
		return x.CrudTypes
	}
	return nil
}

func (x *ProjectionsRegisterMigrationRequest) GetEnums() []*ProjectionsEnumType {
	if x != nil {
		return x.Enums
	}
	return nil
}

func (x *ProjectionsRegisterMigrationRequest) GetNestedTypes() []*ProjectionsNestedType {
	if x != nil {
		return x.NestedTypes
	}
	return nil
}

type ProjectionsRegisterMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProjectionsRegisterMigrationResponse) Reset() {
	*x = ProjectionsRegisterMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectionsRegisterMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionsRegisterMigrationResponse) ProtoMessage() {}

func (x *ProjectionsRegisterMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionsRegisterMigrationResponse.ProtoReflect.Descriptor instead.
func (*ProjectionsRegisterMigrationResponse) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{8}
}

type ProjectionsStartMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProjectionsStartMigrationRequest) Reset() {
	*x = ProjectionsStartMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectionsStartMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionsStartMigrationRequest) ProtoMessage() {}

func (x *ProjectionsStartMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionsStartMigrationRequest.ProtoReflect.Descriptor instead.
func (*ProjectionsStartMigrationRequest) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{9}
}

type ProjectionsStartMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProjectionsStartMigrationResponse) Reset() {
	*x = ProjectionsStartMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectionsStartMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionsStartMigrationResponse) ProtoMessage() {}

func (x *ProjectionsStartMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionsStartMigrationResponse.ProtoReflect.Descriptor instead.
func (*ProjectionsStartMigrationResponse) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{10}
}

type ProjectionsFinishMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProjectionsFinishMigrationRequest) Reset() {
	*x = ProjectionsFinishMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectionsFinishMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionsFinishMigrationRequest) ProtoMessage() {}

func (x *ProjectionsFinishMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionsFinishMigrationRequest.ProtoReflect.Descriptor instead.
func (*ProjectionsFinishMigrationRequest) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{11}
}

type ProjectionsFinishMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProjectionsFinishMigrationResponse) Reset() {
	*x = ProjectionsFinishMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectionsFinishMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionsFinishMigrationResponse) ProtoMessage() {}

func (x *ProjectionsFinishMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionsFinishMigrationResponse.ProtoReflect.Descriptor instead.
func (*ProjectionsFinishMigrationResponse) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{12}
}

type ProjectionsRollbackMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProjectionsRollbackMigrationRequest) Reset() {
	*x = ProjectionsRollbackMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectionsRollbackMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionsRollbackMigrationRequest) ProtoMessage() {}

func (x *ProjectionsRollbackMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionsRollbackMigrationRequest.ProtoReflect.Descriptor instead.
func (*ProjectionsRollbackMigrationRequest) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{13}
}

type ProjectionsRollbackMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProjectionsRollbackMigrationResponse) Reset() {
	*x = ProjectionsRollbackMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectionsRollbackMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionsRollbackMigrationResponse) ProtoMessage() {}

func (x *ProjectionsRollbackMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionsRollbackMigrationResponse.ProtoReflect.Descriptor instead.
func (*ProjectionsRollbackMigrationResponse) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{14}
}

type ProjectionsGetMigrationStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProjectionsGetMigrationStatusRequest) Reset() {
	*x = ProjectionsGetMigrationStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectionsGetMigrationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionsGetMigrationStatusRequest) ProtoMessage() {}

func (x *ProjectionsGetMigrationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionsGetMigrationStatusRequest.ProtoReflect.Descriptor instead.
func (*ProjectionsGetMigrationStatusRequest) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{15}
}

type ProjectionsGetMigrationStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Started bool `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	Done    bool `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
}

func (x *ProjectionsGetMigrationStatusResponse) Reset() {
	*x = ProjectionsGetMigrationStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_migration_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectionsGetMigrationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionsGetMigrationStatusResponse) ProtoMessage() {}

func (x *ProjectionsGetMigrationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_migration_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionsGetMigrationStatusResponse.ProtoReflect.Descriptor instead.
func (*ProjectionsGetMigrationStatusResponse) Descriptor() ([]byte, []int) {
	return file_management_migration_proto_rawDescGZIP(), []int{16}
}

func (x *ProjectionsGetMigrationStatusResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *ProjectionsGetMigrationStatusResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_management_migration_proto protoreflect.FileDescriptor

var file_management_migration_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x6d, 0x69, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x41, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x75, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0xaf, 0x01, 0x0a, 0x19,
	0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x50, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x44, 0x0a,
	0x0a, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x54, 0x79, 0x70, 0x65, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x52, 0x0a, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x73, 0x12, 0x38, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x54, 0x79, 0x70, 0x65,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0xa9, 0x01,
	0x0a, 0x13, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x43, 0x72, 0x75,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x44, 0x0a, 0x0a, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x54, 0x79, 0x70, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x52, 0x0a, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x12,
	0x38, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x54, 0x79, 0x70, 0x65, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0xab, 0x01, 0x0a, 0x15, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x44, 0x0a, 0x0a, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x54, 0x79, 0x70, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x52, 0x0a, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x12, 0x38, 0x0a,
	0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x54, 0x79, 0x70, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52,
	0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x84, 0x01, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x54, 0x79, 0x70, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x44, 0x0a, 0x0a, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x54, 0x79, 0x70, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x52, 0x0a, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x22, 0x71,
	0x0a, 0x18, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x54, 0x79, 0x70,
	0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x41,
	0x0a, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x54, 0x79, 0x70, 0x65, 0x41, 0x72,
	0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x22, 0x43, 0x0a, 0x17, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x54, 0x79, 0x70, 0x65, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xf3, 0x02, 0x0a, 0x23, 0x50, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x69,
	0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40,
	0x0a, 0x1b, 0x64, 0x61, 0x6e, 0x67, 0x65, 0x72, 0x6f, 0x75, 0x73, 0x6c, 0x79, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x47, 0x64, 0x70, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x1b, 0x64, 0x61, 0x6e, 0x67, 0x65, 0x72, 0x6f, 0x75, 0x73, 0x6c, 0x79,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x47, 0x64, 0x70, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x12, 0x4f, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x12, 0x3d, 0x0a, 0x09, 0x63, 0x72, 0x75, 0x64, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x43, 0x72, 0x75,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x63, 0x72, 0x75, 0x64, 0x54, 0x79, 0x70, 0x65, 0x73,
	0x12, 0x35, 0x0a, 0x05, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x75, 0x6d, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x05, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x12, 0x43, 0x0a, 0x0b, 0x6e, 0x65, 0x73, 0x74, 0x65,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x0b, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x73, 0x22, 0x26, 0x0a, 0x24,
	0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x22, 0x0a, 0x20, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x23, 0x0a, 0x21, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x69, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x23, 0x0a,
	0x21, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x46, 0x69, 0x6e, 0x69,
	0x73, 0x68, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x24, 0x0a, 0x22, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x25, 0x0a, 0x23, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x4d,
	0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x26, 0x0a, 0x24, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x6f,
	0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x26, 0x0a, 0x24, 0x50, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x55, 0x0a, 0x25, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x47, 0x65,
	0x74, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_management_migration_proto_rawDescOnce sync.Once
	file_management_migration_proto_rawDescData = file_management_migration_proto_rawDesc
)

func file_management_migration_proto_rawDescGZIP() []byte {
	file_management_migration_proto_rawDescOnce.Do(func() {
		file_management_migration_proto_rawDescData = protoimpl.X.CompressGZIP(file_management_migration_proto_rawDescData)
	})
	return file_management_migration_proto_rawDescData
}

var file_management_migration_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_management_migration_proto_goTypes = []interface{}{
	(*ProjectionsEnumType)(nil),                   // 0: management.ProjectionsEnumType
	(*ProjectionsProjectionType)(nil),             // 1: management.ProjectionsProjectionType
	(*ProjectionsCrudType)(nil),                   // 2: management.ProjectionsCrudType
	(*ProjectionsNestedType)(nil),                 // 3: management.ProjectionsNestedType
	(*ProjectionsTypeField)(nil),                  // 4: management.ProjectionsTypeField
	(*ProjectionsTypeDirective)(nil),              // 5: management.ProjectionsTypeDirective
	(*ProjectionsTypeArgument)(nil),               // 6: management.ProjectionsTypeArgument
	(*ProjectionsRegisterMigrationRequest)(nil),   // 7: management.ProjectionsRegisterMigrationRequest
	(*ProjectionsRegisterMigrationResponse)(nil),  // 8: management.ProjectionsRegisterMigrationResponse
	(*ProjectionsStartMigrationRequest)(nil),      // 9: management.ProjectionsStartMigrationRequest
	(*ProjectionsStartMigrationResponse)(nil),     // 10: management.ProjectionsStartMigrationResponse
	(*ProjectionsFinishMigrationRequest)(nil),     // 11: management.ProjectionsFinishMigrationRequest
	(*ProjectionsFinishMigrationResponse)(nil),    // 12: management.ProjectionsFinishMigrationResponse
	(*ProjectionsRollbackMigrationRequest)(nil),   // 13: management.ProjectionsRollbackMigrationRequest
	(*ProjectionsRollbackMigrationResponse)(nil),  // 14: management.ProjectionsRollbackMigrationResponse
	(*ProjectionsGetMigrationStatusRequest)(nil),  // 15: management.ProjectionsGetMigrationStatusRequest
	(*ProjectionsGetMigrationStatusResponse)(nil), // 16: management.ProjectionsGetMigrationStatusResponse
}
var file_management_migration_proto_depIdxs = []int32{
	5,  // 0: management.ProjectionsProjectionType.directives:type_name -> management.ProjectionsTypeDirective
	4,  // 1: management.ProjectionsProjectionType.fields:type_name -> management.ProjectionsTypeField
	5,  // 2: management.ProjectionsCrudType.directives:type_name -> management.ProjectionsTypeDirective
	4,  // 3: management.ProjectionsCrudType.fields:type_name -> management.ProjectionsTypeField
	5,  // 4: management.ProjectionsNestedType.directives:type_name -> management.ProjectionsTypeDirective
	4,  // 5: management.ProjectionsNestedType.fields:type_name -> management.ProjectionsTypeField
	5,  // 6: management.ProjectionsTypeField.directives:type_name -> management.ProjectionsTypeDirective
	6,  // 7: management.ProjectionsTypeDirective.arguments:type_name -> management.ProjectionsTypeArgument
	1,  // 8: management.ProjectionsRegisterMigrationRequest.projectionTypes:type_name -> management.ProjectionsProjectionType
	2,  // 9: management.ProjectionsRegisterMigrationRequest.crudTypes:type_name -> management.ProjectionsCrudType
	0,  // 10: management.ProjectionsRegisterMigrationRequest.enums:type_name -> management.ProjectionsEnumType
	3,  // 11: management.ProjectionsRegisterMigrationRequest.nestedTypes:type_name -> management.ProjectionsNestedType
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_management_migration_proto_init() }
func file_management_migration_proto_init() {
	if File_management_migration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_management_migration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectionsEnumType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_migration_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectionsProjectionType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_migration_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectionsCrudType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_migration_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectionsNestedType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_migration_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectionsTypeField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_migration_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectionsTypeDirective); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_migration_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectionsTypeArgument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_migration_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectionsRegisterMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_migration_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectionsRegisterMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_migration_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectionsStartMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_migration_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectionsStartMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_migration_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectionsFinishMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_migration_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectionsFinishMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_migration_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectionsRollbackMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_migration_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectionsRollbackMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_migration_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectionsGetMigrationStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_migration_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectionsGetMigrationStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_management_migration_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_management_migration_proto_goTypes,
		DependencyIndexes: file_management_migration_proto_depIdxs,
		MessageInfos:      file_management_migration_proto_msgTypes,
	}.Build()
	File_management_migration_proto = out.File
	file_management_migration_proto_rawDesc = nil
	file_management_migration_proto_goTypes = nil
	file_management_migration_proto_depIdxs = nil
}
