// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: management/projections_migration.proto

package managementpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *EnumType) Reset() {
	*x = EnumType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_projections_migration_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnumType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumType) ProtoMessage() {}

func (x *EnumType) ProtoReflect() protoreflect.Message {
	mi := &file_management_projections_migration_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumType.ProtoReflect.Descriptor instead.
func (*EnumType) Descriptor() ([]byte, []int) {
	return file_management_projections_migration_proto_rawDescGZIP(), []int{0}
}

func (x *EnumType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnumType) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type ProjectionType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Directives []*TypeDirective `protobuf:"bytes,2,rep,name=directives,proto3" json:"directives,omitempty"`
	Fields     []*TypeField     `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *ProjectionType) Reset() {
	*x = ProjectionType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_projections_migration_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectionType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionType) ProtoMessage() {}

func (x *ProjectionType) ProtoReflect() protoreflect.Message {
	mi := &file_management_projections_migration_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionType.ProtoReflect.Descriptor instead.
func (*ProjectionType) Descriptor() ([]byte, []int) {
	return file_management_projections_migration_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectionType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectionType) GetDirectives() []*TypeDirective {
	if x != nil {
		return x.Directives
	}
	return nil
}

func (x *ProjectionType) GetFields() []*TypeField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type CrudType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Directives []*TypeDirective `protobuf:"bytes,2,rep,name=directives,proto3" json:"directives,omitempty"`
	Fields     []*TypeField     `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *CrudType) Reset() {
	*x = CrudType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_projections_migration_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrudType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrudType) ProtoMessage() {}

func (x *CrudType) ProtoReflect() protoreflect.Message {
	mi := &file_management_projections_migration_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrudType.ProtoReflect.Descriptor instead.
func (*CrudType) Descriptor() ([]byte, []int) {
	return file_management_projections_migration_proto_rawDescGZIP(), []int{2}
}

func (x *CrudType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CrudType) GetDirectives() []*TypeDirective {
	if x != nil {
		return x.Directives
	}
	return nil
}

func (x *CrudType) GetFields() []*TypeField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type NestedType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Directives []*TypeDirective `protobuf:"bytes,2,rep,name=directives,proto3" json:"directives,omitempty"`
	Fields     []*TypeField     `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *NestedType) Reset() {
	*x = NestedType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_projections_migration_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NestedType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedType) ProtoMessage() {}

func (x *NestedType) ProtoReflect() protoreflect.Message {
	mi := &file_management_projections_migration_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedType.ProtoReflect.Descriptor instead.
func (*NestedType) Descriptor() ([]byte, []int) {
	return file_management_projections_migration_proto_rawDescGZIP(), []int{3}
}

func (x *NestedType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NestedType) GetDirectives() []*TypeDirective {
	if x != nil {
		return x.Directives
	}
	return nil
}

func (x *NestedType) GetFields() []*TypeField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type TypeField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type       []string         `protobuf:"bytes,2,rep,name=type,proto3" json:"type,omitempty"`
	Directives []*TypeDirective `protobuf:"bytes,3,rep,name=directives,proto3" json:"directives,omitempty"`
}

func (x *TypeField) Reset() {
	*x = TypeField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_projections_migration_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypeField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeField) ProtoMessage() {}

func (x *TypeField) ProtoReflect() protoreflect.Message {
	mi := &file_management_projections_migration_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeField.ProtoReflect.Descriptor instead.
func (*TypeField) Descriptor() ([]byte, []int) {
	return file_management_projections_migration_proto_rawDescGZIP(), []int{4}
}

func (x *TypeField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TypeField) GetType() []string {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *TypeField) GetDirectives() []*TypeDirective {
	if x != nil {
		return x.Directives
	}
	return nil
}

type TypeDirective struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments []*TypeArgument `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty"`
}

func (x *TypeDirective) Reset() {
	*x = TypeDirective{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_projections_migration_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypeDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeDirective) ProtoMessage() {}

func (x *TypeDirective) ProtoReflect() protoreflect.Message {
	mi := &file_management_projections_migration_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeDirective.ProtoReflect.Descriptor instead.
func (*TypeDirective) Descriptor() ([]byte, []int) {
	return file_management_projections_migration_proto_rawDescGZIP(), []int{5}
}

func (x *TypeDirective) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TypeDirective) GetArguments() []*TypeArgument {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type TypeArgument struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *TypeArgument) Reset() {
	*x = TypeArgument{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_projections_migration_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TypeArgument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeArgument) ProtoMessage() {}

func (x *TypeArgument) ProtoReflect() protoreflect.Message {
	mi := &file_management_projections_migration_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeArgument.ProtoReflect.Descriptor instead.
func (*TypeArgument) Descriptor() ([]byte, []int) {
	return file_management_projections_migration_proto_rawDescGZIP(), []int{6}
}

func (x *TypeArgument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TypeArgument) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RegisterMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DangerouslyRemoveGdprFields bool              `protobuf:"varint,1,opt,name=dangerouslyRemoveGdprFields,proto3" json:"dangerouslyRemoveGdprFields,omitempty"`
	ProjectionTypes             []*ProjectionType `protobuf:"bytes,2,rep,name=projectionTypes,proto3" json:"projectionTypes,omitempty"`
	CrudTypes                   []*CrudType       `protobuf:"bytes,3,rep,name=crudTypes,proto3" json:"crudTypes,omitempty"`
	Enums                       []*EnumType       `protobuf:"bytes,4,rep,name=enums,proto3" json:"enums,omitempty"`
	NestedTypes                 []*NestedType     `protobuf:"bytes,5,rep,name=nestedTypes,proto3" json:"nestedTypes,omitempty"`
}

func (x *RegisterMigrationRequest) Reset() {
	*x = RegisterMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_projections_migration_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMigrationRequest) ProtoMessage() {}

func (x *RegisterMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_projections_migration_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMigrationRequest.ProtoReflect.Descriptor instead.
func (*RegisterMigrationRequest) Descriptor() ([]byte, []int) {
	return file_management_projections_migration_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterMigrationRequest) GetDangerouslyRemoveGdprFields() bool {
	if x != nil {
		return x.DangerouslyRemoveGdprFields
	}
	return false
}

func (x *RegisterMigrationRequest) GetProjectionTypes() []*ProjectionType {
	if x != nil {
		return x.ProjectionTypes
	}
	return nil
}

func (x *RegisterMigrationRequest) GetCrudTypes() []*CrudType {
	if x != nil {
		return x.CrudTypes
	}
	return nil
}

func (x *RegisterMigrationRequest) GetEnums() []*EnumType {
	if x != nil {
		return x.Enums
	}
	return nil
}

func (x *RegisterMigrationRequest) GetNestedTypes() []*NestedType {
	if x != nil {
		return x.NestedTypes
	}
	return nil
}

type RegisterMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterMigrationResponse) Reset() {
	*x = RegisterMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_projections_migration_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMigrationResponse) ProtoMessage() {}

func (x *RegisterMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_projections_migration_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMigrationResponse.ProtoReflect.Descriptor instead.
func (*RegisterMigrationResponse) Descriptor() ([]byte, []int) {
	return file_management_projections_migration_proto_rawDescGZIP(), []int{8}
}

type StartMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartMigrationRequest) Reset() {
	*x = StartMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_projections_migration_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMigrationRequest) ProtoMessage() {}

func (x *StartMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_projections_migration_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMigrationRequest.ProtoReflect.Descriptor instead.
func (*StartMigrationRequest) Descriptor() ([]byte, []int) {
	return file_management_projections_migration_proto_rawDescGZIP(), []int{9}
}

type StartMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartMigrationResponse) Reset() {
	*x = StartMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_projections_migration_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMigrationResponse) ProtoMessage() {}

func (x *StartMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_projections_migration_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMigrationResponse.ProtoReflect.Descriptor instead.
func (*StartMigrationResponse) Descriptor() ([]byte, []int) {
	return file_management_projections_migration_proto_rawDescGZIP(), []int{10}
}

type FinishMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinishMigrationRequest) Reset() {
	*x = FinishMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_projections_migration_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishMigrationRequest) ProtoMessage() {}

func (x *FinishMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_projections_migration_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishMigrationRequest.ProtoReflect.Descriptor instead.
func (*FinishMigrationRequest) Descriptor() ([]byte, []int) {
	return file_management_projections_migration_proto_rawDescGZIP(), []int{11}
}

type FinishMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinishMigrationResponse) Reset() {
	*x = FinishMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_projections_migration_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishMigrationResponse) ProtoMessage() {}

func (x *FinishMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_projections_migration_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishMigrationResponse.ProtoReflect.Descriptor instead.
func (*FinishMigrationResponse) Descriptor() ([]byte, []int) {
	return file_management_projections_migration_proto_rawDescGZIP(), []int{12}
}

type RollbackMigrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RollbackMigrationRequest) Reset() {
	*x = RollbackMigrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_projections_migration_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollbackMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackMigrationRequest) ProtoMessage() {}

func (x *RollbackMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_projections_migration_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackMigrationRequest.ProtoReflect.Descriptor instead.
func (*RollbackMigrationRequest) Descriptor() ([]byte, []int) {
	return file_management_projections_migration_proto_rawDescGZIP(), []int{13}
}

type RollbackMigrationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RollbackMigrationResponse) Reset() {
	*x = RollbackMigrationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_projections_migration_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RollbackMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackMigrationResponse) ProtoMessage() {}

func (x *RollbackMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_projections_migration_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackMigrationResponse.ProtoReflect.Descriptor instead.
func (*RollbackMigrationResponse) Descriptor() ([]byte, []int) {
	return file_management_projections_migration_proto_rawDescGZIP(), []int{14}
}

type GetMigrationStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMigrationStatusRequest) Reset() {
	*x = GetMigrationStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_projections_migration_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMigrationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationStatusRequest) ProtoMessage() {}

func (x *GetMigrationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_projections_migration_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetMigrationStatusRequest) Descriptor() ([]byte, []int) {
	return file_management_projections_migration_proto_rawDescGZIP(), []int{15}
}

type GetMigrationStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Started bool `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	Done    bool `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
}

func (x *GetMigrationStatusResponse) Reset() {
	*x = GetMigrationStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_projections_migration_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMigrationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationStatusResponse) ProtoMessage() {}

func (x *GetMigrationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_projections_migration_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationStatusResponse.ProtoReflect.Descriptor instead.
func (*GetMigrationStatusResponse) Descriptor() ([]byte, []int) {
	return file_management_projections_migration_proto_rawDescGZIP(), []int{16}
}

func (x *GetMigrationStatusResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *GetMigrationStatusResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_management_projections_migration_proto protoreflect.FileDescriptor

var file_management_projections_migration_proto_rawDesc = []byte{
	0x0a, 0x26, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x22, 0x36, 0x0a, 0x08, 0x45, 0x6e, 0x75, 0x6d, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0x8e, 0x01, 0x0a,
	0x0e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x52, 0x0a, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x12, 0x2d,
	0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x88, 0x01,
	0x0a, 0x08, 0x43, 0x72, 0x75, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x39,
	0x0a, 0x0a, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e,
	0x54, 0x79, 0x70, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x52, 0x0a, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x06, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x8a, 0x01, 0x0a, 0x0a, 0x4e, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x79, 0x70,
	0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x52, 0x0a, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x6e, 0x0a, 0x09, 0x54, 0x79, 0x70, 0x65, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x52, 0x0a, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x73, 0x22, 0x5b, 0x0a, 0x0d, 0x54, 0x79, 0x70, 0x65, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x36, 0x0a, 0x09, 0x61, 0x72,
	0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x41,
	0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x22, 0x38, 0x0a, 0x0c, 0x54, 0x79, 0x70, 0x65, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xbc, 0x02, 0x0a,
	0x18, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x1b, 0x64, 0x61, 0x6e,
	0x67, 0x65, 0x72, 0x6f, 0x75, 0x73, 0x6c, 0x79, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x47, 0x64,
	0x70, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x1b,
	0x64, 0x61, 0x6e, 0x67, 0x65, 0x72, 0x6f, 0x75, 0x73, 0x6c, 0x79, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x47, 0x64, 0x70, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x44, 0x0a, 0x0f, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x12, 0x32, 0x0a, 0x09, 0x63, 0x72, 0x75, 0x64, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x43, 0x72, 0x75, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x63, 0x72, 0x75, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x05, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x65, 0x6e, 0x75, 0x6d,
	0x73, 0x12, 0x38, 0x0a, 0x0b, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x2e, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b,
	0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x73, 0x22, 0x1b, 0x0a, 0x19, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x0a, 0x16, 0x46,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4d,
	0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x1a, 0x0a, 0x18, 0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x4d, 0x69, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1b, 0x0a, 0x19,
	0x52, 0x6f, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x0a, 0x19, 0x47, 0x65, 0x74,
	0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4a, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x4d, 0x69, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x6f,
	0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_management_projections_migration_proto_rawDescOnce sync.Once
	file_management_projections_migration_proto_rawDescData = file_management_projections_migration_proto_rawDesc
)

func file_management_projections_migration_proto_rawDescGZIP() []byte {
	file_management_projections_migration_proto_rawDescOnce.Do(func() {
		file_management_projections_migration_proto_rawDescData = protoimpl.X.CompressGZIP(file_management_projections_migration_proto_rawDescData)
	})
	return file_management_projections_migration_proto_rawDescData
}

var file_management_projections_migration_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_management_projections_migration_proto_goTypes = []interface{}{
	(*EnumType)(nil),                   // 0: management.EnumType
	(*ProjectionType)(nil),             // 1: management.ProjectionType
	(*CrudType)(nil),                   // 2: management.CrudType
	(*NestedType)(nil),                 // 3: management.NestedType
	(*TypeField)(nil),                  // 4: management.TypeField
	(*TypeDirective)(nil),              // 5: management.TypeDirective
	(*TypeArgument)(nil),               // 6: management.TypeArgument
	(*RegisterMigrationRequest)(nil),   // 7: management.RegisterMigrationRequest
	(*RegisterMigrationResponse)(nil),  // 8: management.RegisterMigrationResponse
	(*StartMigrationRequest)(nil),      // 9: management.StartMigrationRequest
	(*StartMigrationResponse)(nil),     // 10: management.StartMigrationResponse
	(*FinishMigrationRequest)(nil),     // 11: management.FinishMigrationRequest
	(*FinishMigrationResponse)(nil),    // 12: management.FinishMigrationResponse
	(*RollbackMigrationRequest)(nil),   // 13: management.RollbackMigrationRequest
	(*RollbackMigrationResponse)(nil),  // 14: management.RollbackMigrationResponse
	(*GetMigrationStatusRequest)(nil),  // 15: management.GetMigrationStatusRequest
	(*GetMigrationStatusResponse)(nil), // 16: management.GetMigrationStatusResponse
}
var file_management_projections_migration_proto_depIdxs = []int32{
	5,  // 0: management.ProjectionType.directives:type_name -> management.TypeDirective
	4,  // 1: management.ProjectionType.fields:type_name -> management.TypeField
	5,  // 2: management.CrudType.directives:type_name -> management.TypeDirective
	4,  // 3: management.CrudType.fields:type_name -> management.TypeField
	5,  // 4: management.NestedType.directives:type_name -> management.TypeDirective
	4,  // 5: management.NestedType.fields:type_name -> management.TypeField
	5,  // 6: management.TypeField.directives:type_name -> management.TypeDirective
	6,  // 7: management.TypeDirective.arguments:type_name -> management.TypeArgument
	1,  // 8: management.RegisterMigrationRequest.projectionTypes:type_name -> management.ProjectionType
	2,  // 9: management.RegisterMigrationRequest.crudTypes:type_name -> management.CrudType
	0,  // 10: management.RegisterMigrationRequest.enums:type_name -> management.EnumType
	3,  // 11: management.RegisterMigrationRequest.nestedTypes:type_name -> management.NestedType
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_management_projections_migration_proto_init() }
func file_management_projections_migration_proto_init() {
	if File_management_projections_migration_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_management_projections_migration_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnumType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_projections_migration_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectionType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_projections_migration_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrudType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_projections_migration_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NestedType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_projections_migration_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TypeField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_projections_migration_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TypeDirective); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_projections_migration_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TypeArgument); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_projections_migration_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_projections_migration_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_projections_migration_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_projections_migration_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_projections_migration_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_projections_migration_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_projections_migration_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RollbackMigrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_projections_migration_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RollbackMigrationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_projections_migration_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMigrationStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_projections_migration_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMigrationStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_management_projections_migration_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_management_projections_migration_proto_goTypes,
		DependencyIndexes: file_management_projections_migration_proto_depIdxs,
		MessageInfos:      file_management_projections_migration_proto_msgTypes,
	}.Build()
	File_management_projections_migration_proto = out.File
	file_management_projections_migration_proto_rawDesc = nil
	file_management_projections_migration_proto_goTypes = nil
	file_management_projections_migration_proto_depIdxs = nil
}
