// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: delivery/get_projection_data.proto

package deliverypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProjectionDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Projection                string      `protobuf:"bytes,1,opt,name=projection,proto3" json:"projection,omitempty"`
	Auth                      *AuthData   `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	DataId                    string      `protobuf:"bytes,3,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	Filter                    *DataFilter `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	ReturnEmptyDataIfNotFound bool        `protobuf:"varint,5,opt,name=returnEmptyDataIfNotFound,proto3" json:"returnEmptyDataIfNotFound,omitempty"`
	Wait                      *DataWait   `protobuf:"bytes,6,opt,name=wait,proto3" json:"wait,omitempty"`
}

func (x *GetProjectionDataRequest) Reset() {
	*x = GetProjectionDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_get_projection_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProjectionDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectionDataRequest) ProtoMessage() {}

func (x *GetProjectionDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_get_projection_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectionDataRequest.ProtoReflect.Descriptor instead.
func (*GetProjectionDataRequest) Descriptor() ([]byte, []int) {
	return file_delivery_get_projection_data_proto_rawDescGZIP(), []int{0}
}

func (x *GetProjectionDataRequest) GetProjection() string {
	if x != nil {
		return x.Projection
	}
	return ""
}

func (x *GetProjectionDataRequest) GetAuth() *AuthData {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *GetProjectionDataRequest) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *GetProjectionDataRequest) GetFilter() *DataFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GetProjectionDataRequest) GetReturnEmptyDataIfNotFound() bool {
	if x != nil {
		return x.ReturnEmptyDataIfNotFound
	}
	return false
}

func (x *GetProjectionDataRequest) GetWait() *DataWait {
	if x != nil {
		return x.Wait
	}
	return nil
}

type GetProjectionDataListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Projection string       `protobuf:"bytes,1,opt,name=projection,proto3" json:"projection,omitempty"`
	Auth       *AuthData    `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	Limit      int64        `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Page       int64        `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Filter     *DataFilter  `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	Order      []*DataOrder `protobuf:"bytes,6,rep,name=order,proto3" json:"order,omitempty"`
}

func (x *GetProjectionDataListRequest) Reset() {
	*x = GetProjectionDataListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_get_projection_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProjectionDataListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectionDataListRequest) ProtoMessage() {}

func (x *GetProjectionDataListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_get_projection_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectionDataListRequest.ProtoReflect.Descriptor instead.
func (*GetProjectionDataListRequest) Descriptor() ([]byte, []int) {
	return file_delivery_get_projection_data_proto_rawDescGZIP(), []int{1}
}

func (x *GetProjectionDataListRequest) GetProjection() string {
	if x != nil {
		return x.Projection
	}
	return ""
}

func (x *GetProjectionDataListRequest) GetAuth() *AuthData {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *GetProjectionDataListRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetProjectionDataListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetProjectionDataListRequest) GetFilter() *DataFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GetProjectionDataListRequest) GetOrder() []*DataOrder {
	if x != nil {
		return x.Order
	}
	return nil
}

type DataWait struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConditionFilter *DataFilter `protobuf:"bytes,1,opt,name=conditionFilter,proto3" json:"conditionFilter,omitempty"`
	Timeout         int64       `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *DataWait) Reset() {
	*x = DataWait{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_get_projection_data_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataWait) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataWait) ProtoMessage() {}

func (x *DataWait) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_get_projection_data_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataWait.ProtoReflect.Descriptor instead.
func (*DataWait) Descriptor() ([]byte, []int) {
	return file_delivery_get_projection_data_proto_rawDescGZIP(), []int{2}
}

func (x *DataWait) GetConditionFilter() *DataFilter {
	if x != nil {
		return x.ConditionFilter
	}
	return nil
}

func (x *DataWait) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type DataOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field      string `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Descending bool   `protobuf:"varint,2,opt,name=descending,proto3" json:"descending,omitempty"`
}

func (x *DataOrder) Reset() {
	*x = DataOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_get_projection_data_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataOrder) ProtoMessage() {}

func (x *DataOrder) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_get_projection_data_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataOrder.ProtoReflect.Descriptor instead.
func (*DataOrder) Descriptor() ([]byte, []int) {
	return file_delivery_get_projection_data_proto_rawDescGZIP(), []int{3}
}

func (x *DataOrder) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *DataOrder) GetDescending() bool {
	if x != nil {
		return x.Descending
	}
	return false
}

type ProjectionData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data map[string]string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ProjectionData) Reset() {
	*x = ProjectionData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_get_projection_data_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionData) ProtoMessage() {}

func (x *ProjectionData) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_get_projection_data_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionData.ProtoReflect.Descriptor instead.
func (*ProjectionData) Descriptor() ([]byte, []int) {
	return file_delivery_get_projection_data_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectionData) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetProjectionDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *ProjectionData `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GetProjectionDataResponse) Reset() {
	*x = GetProjectionDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_get_projection_data_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProjectionDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectionDataResponse) ProtoMessage() {}

func (x *GetProjectionDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_get_projection_data_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectionDataResponse.ProtoReflect.Descriptor instead.
func (*GetProjectionDataResponse) Descriptor() ([]byte, []int) {
	return file_delivery_get_projection_data_proto_rawDescGZIP(), []int{5}
}

func (x *GetProjectionDataResponse) GetResult() *ProjectionData {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetProjectionDataListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*ProjectionData `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Limit  int64             `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page   int64             `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Total  int64             `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *GetProjectionDataListResponse) Reset() {
	*x = GetProjectionDataListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_get_projection_data_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetProjectionDataListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectionDataListResponse) ProtoMessage() {}

func (x *GetProjectionDataListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_get_projection_data_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectionDataListResponse.ProtoReflect.Descriptor instead.
func (*GetProjectionDataListResponse) Descriptor() ([]byte, []int) {
	return file_delivery_get_projection_data_proto_rawDescGZIP(), []int{6}
}

func (x *GetProjectionDataListResponse) GetResult() []*ProjectionData {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetProjectionDataListResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetProjectionDataListResponse) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetProjectionDataListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_delivery_get_projection_data_proto protoreflect.FileDescriptor

var file_delivery_get_projection_data_proto_rawDesc = []byte{
	0x0a, 0x22, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2f, 0x67, 0x65, 0x74, 0x5f, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x1a, 0x15,
	0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8f, 0x02, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x61, 0x74,
	0x61, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x12, 0x3c, 0x0a, 0x19, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x44, 0x61, 0x74, 0x61, 0x49, 0x66, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x19, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x44, 0x61, 0x74, 0x61, 0x49, 0x66, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x12,
	0x26, 0x0a, 0x04, 0x77, 0x61, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x57, 0x61, 0x69,
	0x74, 0x52, 0x04, 0x77, 0x61, 0x69, 0x74, 0x22, 0xe9, 0x01, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x50,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x79, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x65, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x29, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x22, 0x64, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x57, 0x61, 0x69, 0x74, 0x12,
	0x3e, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x0f,
	0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x41, 0x0a, 0x09, 0x44, 0x61, 0x74,
	0x61, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x64, 0x65, 0x73, 0x63, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x64, 0x65, 0x73, 0x63, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x81, 0x01, 0x0a,
	0x0e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x36, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x37, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x4d, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x91, 0x01, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x30, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_delivery_get_projection_data_proto_rawDescOnce sync.Once
	file_delivery_get_projection_data_proto_rawDescData = file_delivery_get_projection_data_proto_rawDesc
)

func file_delivery_get_projection_data_proto_rawDescGZIP() []byte {
	file_delivery_get_projection_data_proto_rawDescOnce.Do(func() {
		file_delivery_get_projection_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_delivery_get_projection_data_proto_rawDescData)
	})
	return file_delivery_get_projection_data_proto_rawDescData
}

var file_delivery_get_projection_data_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_delivery_get_projection_data_proto_goTypes = []interface{}{
	(*GetProjectionDataRequest)(nil),      // 0: delivery.GetProjectionDataRequest
	(*GetProjectionDataListRequest)(nil),  // 1: delivery.GetProjectionDataListRequest
	(*DataWait)(nil),                      // 2: delivery.DataWait
	(*DataOrder)(nil),                     // 3: delivery.DataOrder
	(*ProjectionData)(nil),                // 4: delivery.ProjectionData
	(*GetProjectionDataResponse)(nil),     // 5: delivery.GetProjectionDataResponse
	(*GetProjectionDataListResponse)(nil), // 6: delivery.GetProjectionDataListResponse
	nil,                                   // 7: delivery.ProjectionData.DataEntry
	(*AuthData)(nil),                      // 8: delivery.AuthData
	(*DataFilter)(nil),                    // 9: delivery.DataFilter
}
var file_delivery_get_projection_data_proto_depIdxs = []int32{
	8,  // 0: delivery.GetProjectionDataRequest.auth:type_name -> delivery.AuthData
	9,  // 1: delivery.GetProjectionDataRequest.filter:type_name -> delivery.DataFilter
	2,  // 2: delivery.GetProjectionDataRequest.wait:type_name -> delivery.DataWait
	8,  // 3: delivery.GetProjectionDataListRequest.auth:type_name -> delivery.AuthData
	9,  // 4: delivery.GetProjectionDataListRequest.filter:type_name -> delivery.DataFilter
	3,  // 5: delivery.GetProjectionDataListRequest.order:type_name -> delivery.DataOrder
	9,  // 6: delivery.DataWait.conditionFilter:type_name -> delivery.DataFilter
	7,  // 7: delivery.ProjectionData.data:type_name -> delivery.ProjectionData.DataEntry
	4,  // 8: delivery.GetProjectionDataResponse.result:type_name -> delivery.ProjectionData
	4,  // 9: delivery.GetProjectionDataListResponse.result:type_name -> delivery.ProjectionData
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_delivery_get_projection_data_proto_init() }
func file_delivery_get_projection_data_proto_init() {
	if File_delivery_get_projection_data_proto != nil {
		return
	}
	file_delivery_shared_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_delivery_get_projection_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProjectionDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_get_projection_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProjectionDataListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_get_projection_data_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataWait); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_get_projection_data_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_get_projection_data_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectionData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_get_projection_data_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProjectionDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_get_projection_data_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetProjectionDataListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_delivery_get_projection_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_delivery_get_projection_data_proto_goTypes,
		DependencyIndexes: file_delivery_get_projection_data_proto_depIdxs,
		MessageInfos:      file_delivery_get_projection_data_proto_msgTypes,
	}.Build()
	File_delivery_get_projection_data_proto = out.File
	file_delivery_get_projection_data_proto_rawDesc = nil
	file_delivery_get_projection_data_proto_goTypes = nil
	file_delivery_get_projection_data_proto_depIdxs = nil
}
